default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%=ENV['DATABASE_USER']%>
  password: <%=ENV['DATABASE_PASSWORD']%>

development:
  <<: *default
  database: restaurant_reservation_development


test:
  <<: *default
  database: restaurant_reservation_test
